name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start database service
        run: docker compose -f docker-compose.yml up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Run Unit Tests
        working-directory: secure-tasks-api
        run: mvn clean test

      - name: Upload build + coverage report
        uses: actions/upload-artifact@master
        with:
          name: build-artifacts
          path: |
            secure-tasks-api/target/classes
            secure-tasks-api/target/test-classes
            secure-tasks-api/target/site/jacoco/jacoco.xml

      - name: Upload Unit Test results
        uses: actions/upload-artifact@master
        with:
           name: Unit test report
           path: ${{github.workspace}}/secure-tasks-api/target/surefire-reports

  dependency-scan:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NIST_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Download Maven dependencies
      #   working-directory: secure-tasks-api
      #   run: mvn dependency:copy-dependencies

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Run OWASP Dependency-Check via Maven
        working-directory: ./secure-tasks-api
        run: mvn org.owasp:dependency-check-maven:check -Dformat=ALL -DfailBuildOnCVSS=7 -DenableRetired=true

      # - name: OWASP Dependency Check
      #   uses: dependency-check/Dependency-Check_Action@main
      #   id: Dpcheck
      #   env:
      #     # actions/setup-java@v1 changes JAVA_HOME so it needs to be reset to match the depcheck image
      #     JAVA_HOME: /opt/jdk
      #   with:
      #     project: 'secure-tasks-api'
      #     path: './secure-tasks-api'
      #     format: ALL
      #     args: >
      #       --failOnCVSS 7
      #       --enableRetired

      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/secure-tasks-api/target
  

  sonarQube:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting.
          fetch-depth: 0


      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      
      - name: Download coverage report
        uses: actions/download-artifact@master
        with:
          name: build-artifacts
          path: secure-tasks-api
      
      - name: Debug file structure
        run: |
          echo "CURRENT DIR:"
          pwd

          echo "FULL TREE:"
          ls -R

          echo "TARGET CHECK:"
          ls -R target || true

          echo "SECURE-TASKS-API CHECK:"
          ls -R secure-tasks-api || true

      - name: SonarQube Scan
        working-directory: ./secure-tasks-api
        run: |
          mvn clean sonar:sonar -DskipTests \
            "-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" \
            "-Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}" \
            "-Dsonar.token=${{ secrets.SONAR_TOKEN }}"

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        timeout-minutes: 5
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: [unit-tests, dependency-scan, sonarQube]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      
      - name: Build Maven project
        working-directory: secure-tasks-api
        run: mvn clean package -DskipTests

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
        
      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Build Docker image
        working-directory: ./secure-tasks-api
        run: docker build -t springboot-app:${{ github.sha }} .
      
      - name: Save Docker image
        run: docker save springboot-app:${{ github.sha }} -o springboot-app-${{ github.sha }}.tar
      
      - name: Copy Docker image to server
        run: scp springboot-app-${{ github.sha }}.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/ciber/springboot-app-${{ github.sha }}.tar

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "

            # Create network
            docker network create springboot-network || true

            # Start Postgres
            docker run -d --name springboot-postgres \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              --network springboot-network \
              postgres:15

            # Load Stpringboot image
            docker load -i ~/ciber/springboot-app-${{ github.sha }}.tar &&
            
            # Stop old container if it exists
            docker stop springboot-app || true &&
            docker rm springboot-app || true &&

            # Wait for postgres
            until docker exec springboot-postgres pg_isready; do
              sleep 1
            done

            # Start new container
            docker run -d --name springboot-app \
              -p 8951:8080 \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -e POSTGRES_HOST=springboot-postgres \
              -e POSTGRES_PORT=5432 \
              -e JWT_SECRET_KEY=\"${{ secrets.JWT_SECRET_KEY }}\" \
              --network springboot-network \
              springboot-app:${{ github.sha }} &&
            rm ~/ciber/springboot-app-${{ github.sha }}.tar &&
            docker image prune -f
          "

